services:
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11-slim
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install -r requirements.txt
        COPY . .
        ENV PYTHONPATH=/app
        CMD ["python", "app/main.py"]
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
