name: CI/CD Pipeline for Dev Environment

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: back1ash/sp_back
  GITOPS_REPO: back1ash/gitops
  MANIFEST_PATH_DIR: apps/fast-api/overlays/dev

jobs:
  build-and-deploy-to-dev:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Image Tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "IMAGE_TAG=$(echo ${{ github.event.pull_request.merge_commit_sha }} | cut -c1-7)" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          fi
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: 'gitops'
          token: ${{ secrets.GITOPS_REPO_PAT }}

      - name: Update Kubernetes manifest using Kustomize
        run: |
          cd gitops
          
          echo "Installing Kustomize..."
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

          echo "Updating image in Kustomization file at ${{ env.MANIFEST_PATH_DIR }}"
          cd ${{ env.MANIFEST_PATH_DIR }}
          kustomize edit set image ${{ env.DOCKER_IMAGE_NAME }}=${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          echo "Committing and pushing changes to GitOps repo..."
          cd -
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploy to dev: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          git push