name: CI/CD Pipeline for Dev Environment

on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

env:
  DOCKER_IMAGE_NAME: back1ash/SP_back  # Docker Hub 사용자 이름/이미지 이름
  GITOPS_REPO: back1ash/gitops      # GitOps 리포지토리 경로
  MANIFEST_PATH_DIR: apps/fast-api/overlays/dev        # Kustomize 업데이트 경로

jobs:
  build-and-deploy-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        id: set_tag
        run: echo "IMAGE_TAG=$(echo ${{ github.event.pull_request.merge_commit_sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: 'gitops'
          token: ${{ secrets.GITOPS_REPO_PAT }}

      - name: Update Kubernetes manifest using Kustomize
        run: |
          cd gitops
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

          cd ${{ env.MANIFEST_PATH_DIR }}
          kustomize edit set image ${{ env.DOCKER_IMAGE_NAME }}=${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cd - # gitops 루트로 돌아가기

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploy to dev: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          git push
